In [40]:
import numpy as np
import pandas as pd
df = pd.read_csv("german_predictions.csv").set_index('OBS#')
df

,CHK_ACCT,DURATION,HISTORY,NEW_CAR,USED_CAR,FURNITURE,RADIO/TV,EDUCATION,RETAINING,SAV_ACCT,...,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,JOB,NUM_DEPENDENTS,TELEPHONE,FOREIGN,AMOUNT
OBS#,,,,,,,,,,,,,,,,,,,,,
0,0,6,4,0,0,0,1,0,0,4,...,67,0,0,1,2,2,1,1,0,1169
1,1,48,2,0,0,0,1,0,0,0,...,22,0,0,1,1,2,1,0,0,5951
2,3,12,4,0,0,0,0,1,0,0,...,49,0,0,1,1,1,2,0,0,2096
3,0,42,2,0,0,1,0,0,0,0,...,45,0,0,0,1,2,2,0,0,7882
4,0,24,3,1,0,0,0,0,0,0,...,53,0,0,0,2,2,2,0,0,4870
5,3,36,2,0,0,0,0,1,0,4,...,35,0,0,0,1,1,2,1,0,9055
6,3,24,2,0,0,1,0,0,0,2,...,53,0,0,1,1,2,1,0,0,2835
7,1,36,2,0,1,0,0,0,0,0,...,35,0,1,0,1,3,1,1,0,6948
8,3,12,2,0,0,0,1,0,0,3,...,61,0,0,1,1,1,1,0,0,3059
9,1,30,4,1,0,0,0,0,0,0,...,28,0,0,1,2,3,1,0,0,5234
10,1,12,2,1,0,0,0,0,0,0,...,25,0,1,0,1,2,1,0,0,1295
11,0,48,2,0,0,0,0,0,0,0,...,24,0,1,0,1,2,1,0,0,4308
12,1,12,2,0,0,0,1,0,0,0,...,22,0,0,1,1,2,1,1,0,1567
13,0,24,4,1,0,0,0,0,0,0,...,60,0,0,1,2,1,1,0,0,1199
14,0,15,2,1,0,0,0,0,0,0,...,28,0,1,0,1,2,1,0,0,1403
15,0,24,2,0,0,0,1,0,0,1,...,32,0,0,1,1,1,1,0,0,1282
16,3,24,4,0,0,0,1,0,0,4,...,53,0,0,1,2,2,1,0,0,2424
17,0,30,0,0,0,0,0,0,0,4,...,25,1,0,1,3,2,1,0,0,8072
18,1,24,2,0,1,0,0,0,0,0,...,44,0,0,0,1,3,1,1,0,12579
19,3,24,2,0,0,0,1,0,0,2,...,31,0,0,1,1,2,2,1,0,3430
20,3,9,4,1,0,0,0,0,0,0,...,48,0,0,1,3,2,1,1,0,2134
21,0,6,2,0,0,0,1,0,0,2,...,44,0,1,0,1,2,2,0,0,2647
22,0,10,4,1,0,0,0,0,0,0,...,48,0,1,0,2,1,2,0,1,2241
23,1,12,4,0,1,0,0,0,0,1,...,44,0,0,1,1,2,1,0,0,1804
24,3,10,4,0,0,1,0,0,0,4,...,26,0,0,1,2,2,1,0,1,2069
25,0,6,2,0,0,1,0,0,0,0,...,36,1,0,1,1,1,1,1,0,1374
26,3,6,0,0,0,0,1,0,0,0,...,39,0,0,1,1,1,1,0,0,426
27,2,12,1,0,0,0,1,0,0,3,...,42,0,1,0,2,2,1,0,0,409
28,1,7,2,0,0,0,1,0,0,0,...,34,0,0,1,1,2,1,0,0,2415
29,0,60,3,0,0,0,0,0,0,0,...,63,0,0,1,2,2,1,1,0,6836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,1,15,2,0,0,0,0,0,0,1,...,22,0,0,1,1,2,1,0,0,1514
971,3,24,2,1,0,0,0,0,0,0,...,43,0,0,1,1,1,2,0,0,7393
972,0,24,1,1,0,0,0,0,0,0,...,29,0,1,0,2,0,1,0,0,1193
973,0,60,2,0,0,0,0,0,0,0,...,36,0,1,0,1,2,1,0,0,7297
974,3,30,4,0,0,0,1,0,0,0,...,33,0,0,1,1,2,1,1,0,2831
975,2,24,2,0,0,0,1,0,0,2,...,57,0,0,1,1,1,1,0,0,1258
976,1,6,2,0,0,0,1,0,0,0,...,64,0,0,1,1,2,1,0,0,753
977,1,18,3,0,0,0,0,0,0,4,...,42,0,0,1,2,2,1,0,0,2427
978,3,24,3,1,0,0,0,0,0,0,...,47,0,0,1,2,1,2,0,0,2538
979,1,15,1,1,0,0,0,0,0,1,...,25,0,1,0,1,2,1,0,0,1264
980,1,30,4,0,0,1,0,0,0,0,...,49,0,0,1,1,2,1,0,0,8386
981,3,48,2,0,0,0,0,0,0,0,...,33,1,1,0,1,3,1,1,0,4844
982,2,21,2,1,0,0,0,0,0,1,...,28,1,0,1,1,3,1,1,0,2923
983,0,36,2,0,1,0,0,0,0,0,...,26,0,0,1,1,2,2,0,0,8229
984,3,24,4,0,0,1,0,0,0,0,...,30,0,0,1,2,1,1,0,0,2028
985,0,15,4,0,0,1,0,0,0,0,...,25,0,1,0,2,2,1,0,0,1433
986,2,42,0,0,0,0,0,0,0,0,...,33,0,0,1,2,2,1,0,0,6289
987,3,13,2,0,0,0,1,0,0,1,...,64,0,0,1,1,2,1,0,0,1409
988,0,24,2,0,1,0,0,0,0,0,...,29,0,0,0,1,3,1,1,0,6579
989,1,24,4,0,0,0,1,0,0,0,...,48,0,0,1,2,1,1,0,0,1743
990,3,12,4,0,0,0,0,1,0,4,...,37,0,0,1,2,1,2,0,0,3565
991,3,15,1,0,0,0,1,0,0,1,...,34,1,0,1,1,1,2,0,0,1569
992,0,18,2,0,0,0,1,0,0,4,...,23,0,1,0,2,1,1,0,0,1936
993,0,36,2,0,0,1,0,0,0,0,...,30,0,0,1,1,3,1,1,0,3959
994,3,12,2,1,0,0,0,0,0,4,...,50,0,0,1,1,2,1,1,0,2390
995,3,12,2,0,0,1,0,0,0,0,...,31,0,0,1,1,1,1,0,0,1736
996,0,30,2,0,1,0,0,0,0,0,...,40,0,0,1,1,3,1,1,0,3857
997,3,12,2,0,0,0,1,0,0,0,...,38,0,0,1,1,2,1,0,0,804
998,0,45,2,0,0,0,1,0,0,0,...,23,0,0,0,1,2,1,1,0,1845
999,1,45,4,0,1,0,0,0,0,1,...,27,0,0,1,1,2,1,0,0,4576

In [4]:
X, y = df.drop('AMOUNT',axis = 1),df.AMOUNT 
# 축을 1로 놓아야 한다! 안그럼 칼럼으로 되니까! 드롭 함수는 axis 0기본이라서. 행이 되어버리기 떄문이지
print(X)

      CHK_ACCT  DURATION  HISTORY  NEW_CAR  USED_CAR  FURNITURE  RADIO/TV  \
OBS#
0            0         6        4        0         0          0         1
1            1        48        2        0         0          0         1
2            3        12        4        0         0          0         0
3            0        42        2        0         0          1         0
4            0        24        3        1         0          0         0
5            3        36        2        0         0          0         0
6            3        24        2        0         0          1         0
7            1        36        2        0         1          0         0
8            3        12        2        0         0          0         1
9            1        30        4        1         0          0         0
10           1        12        2        1         0          0         0
11           0        48        2        0         0          0         0
12           1        12        2        0         0          0         1
13           0        24        4        1         0          0         0
14           0        15        2        1         0          0         0
15           0        24        2        0         0          0         1
16           3        24        4        0         0          0         1
17           0        30        0        0         0          0         0
18           1        24        2        0         1          0         0
19           3        24        2        0         0          0         1
20           3         9        4        1         0          0         0
21           0         6        2        0         0          0         1
22           0        10        4        1         0          0         0
23           1        12        4        0         1          0         0
24           3        10        4        0         0          1         0
25           0         6        2        0         0          1         0
26           3         6        0        0         0          0         1
27           2        12        1        0         0          0         1
28           1         7        2        0         0          0         1
29           0        60        3        0         0          0         0
...        ...       ...      ...      ...       ...        ...       ...
970          1        15        2        0         0          0         0
971          3        24        2        1         0          0         0
972          0        24        1        1         0          0         0
973          0        60        2        0         0          0         0
974          3        30        4        0         0          0         1
975          2        24        2        0         0          0         1
976          1         6        2        0         0          0         1
977          1        18        3        0         0          0         0
978          3        24        3        1         0          0         0
979          1        15        1        1         0          0         0
980          1        30        4        0         0          1         0
981          3        48        2        0         0          0         0
982          2        21        2        1         0          0         0
983          0        36        2        0         1          0         0
984          3        24        4        0         0          1         0
985          0        15        4        0         0          1         0
986          2        42        0        0         0          0         0
987          3        13        2        0         0          0         1
988          0        24        2        0         1          0         0
989          1        24        4        0         0          0         1
990          3        12        4        0         0          0         0
991          3        15        1        0         0          0         1
992          0        18        2        0         0          0         1
993          0        36        2        0         0          1         0
994          3        12        2        1         0          0         0
995          3        12        2        0         0          1         0
996          0        30        2        0         1          0         0
997          3        12        2        0         0          0         1
998          0        45        2        0         0          0         1
999          1        45        4        0         1          0         0

      EDUCATION  RETAINING  SAV_ACCT   ...     PROP_UNKN_NONE  AGE  \
OBS#                                   ...
0             0          0         4   ...                  0   67
1             0          0         0   ...                  0   22
2             1          0         0   ...                  0   49
3             0          0         0   ...                  0   45
4             0          0         0   ...                  1   53
5             1          0         4   ...                  1   35
6             0          0         2   ...                  0   53
7             0          0         0   ...                  0   35
8             0          0         3   ...                  0   61
9             0          0         0   ...                  0   28
10            0          0         0   ...                  0   25
11            0          0         0   ...                  0   24
12            0          0         0   ...                  0   22
13            0          0         0   ...                  0   60
14            0          0         0   ...                  0   28
15            0          0         1   ...                  0   32
16            0          0         4   ...                  0   53
17            0          0         4   ...                  0   25
18            0          0         0   ...                  1   44
19            0          0         2   ...                  0   31
20            0          0         0   ...                  0   48
21            0          0         2   ...                  0   44
22            0          0         0   ...                  0   48
23            0          0         1   ...                  0   44
24            0          0         4   ...                  0   26
25            0          0         0   ...                  0   36
26            0          0         0   ...                  0   39
27            0          0         3   ...                  0   42
28            0          0         0   ...                  0   34
29            0          0         0   ...                  1   63
...         ...        ...       ...   ...                ...  ...
970           0          0         1   ...                  0   22
971           0          0         0   ...                  0   43
972           0          0         0   ...                  1   29
973           0          0         0   ...                  1   36
974           0          0         0   ...                  0   33
975           0          0         2   ...                  0   57
976           0          0         0   ...                  0   64
977           0          0         4   ...                  0   42
978           0          0         0   ...                  0   47
979           0          0         1   ...                  0   25
980           0          0         0   ...                  0   49
981           0          0         0   ...                  0   33
982           0          0         1   ...                  0   28
983           0          0         0   ...                  0   26
984           0          0         0   ...                  0   30
985           0          0         0   ...                  0   25
986           0          0         0   ...                  0   33
987           0          0         1   ...                  0   64
988           0          0         0   ...                  1   29
989           0          0         0   ...                  0   48
990           1          0         4   ...                  0   37
991           0          0         1   ...                  0   34
992           0          0         4   ...                  0   23
993           0          0         0   ...                  0   30
994           0          0         4   ...                  0   50
995           0          0         0   ...                  0   31
996           0          0         0   ...                  0   40
997           0          0         0   ...                  0   38
998           0          0         0   ...                  1   23
999           0          0         1   ...                  0   27

      OTHER_INSTALL  RENT  OWN_RES  NUM_CREDITS  JOB  NUM_DEPENDENTS  \
OBS#
0                 0     0        1            2    2               1
1                 0     0        1            1    2               1
2                 0     0        1            1    1               2
3                 0     0        0            1    2               2
4                 0     0        0            2    2               2
5                 0     0        0            1    1               2
6                 0     0        1            1    2               1
7                 0     1        0            1    3               1
8                 0     0        1            1    1               1
9                 0     0        1            2    3               1
10                0     1        0            1    2               1
11                0     1        0            1    2               1
12                0     0        1            1    2               1
13                0     0        1            2    1               1
14                0     1        0            1    2               1
15                0     0        1            1    1               1
16                0     0        1            2    2               1
17                1     0        1            3    2               1
18                0     0        0            1    3               1
19                0     0        1            1    2               2
20                0     0        1            3    2               1
21                0     1        0            1    2               2
22                0     1        0            2    1               2
23                0     0        1            1    2               1
24                0     0        1            2    2               1
25                1     0        1            1    1               1
26                0     0        1            1    1               1
27                0     1        0            2    2               1
28                0     0        1            1    2               1
29                0     0        1            2    2               1
...             ...   ...      ...          ...  ...             ...
970               0     0        1            1    2               1
971               0     0        1            1    1               2
972               0     1        0            2    0               1
973               0     1        0            1    2               1
974               0     0        1            1    2               1
975               0     0        1            1    1               1
976               0     0        1            1    2               1
977               0     0        1            2    2               1
978               0     0        1            2    1               2
979               0     1        0            1    2               1
980               0     0        1            1    2               1
981               1     1        0            1    3               1
982               1     0        1            1    3               1
983               0     0        1            1    2               2
984               0     0        1            2    1               1
985               0     1        0            2    2               1
986               0     0        1            2    2               1
987               0     0        1            1    2               1
988               0     0        0            1    3               1
989               0     0        1            2    1               1
990               0     0        1            2    1               2
991               1     0        1            1    1               2
992               0     1        0            2    1               1
993               0     0        1            1    3               1
994               0     0        1            1    2               1
995               0     0        1            1    1               1
996               0     0        1            1    3               1
997               0     0        1            1    2               1
998               0     0        0            1    2               1
999               0     0        1            1    2               1

      TELEPHONE  FOREIGN
OBS#
0             1        0
1             0        0
2             0        0
3             0        0
4             0        0
5             1        0
6             0        0
7             1        0
8             0        0
9             0        0
10            0        0
11            0        0
12            1        0
13            0        0
14            0        0
15            0        0
16            0        0
17            0        0
18            1        0
19            1        0
20            1        0
21            0        0
22            0        1
23            0        0
24            0        1
25            1        0
26            0        0
27            0        0
28            0        0
29            1        0
...         ...      ...
970           0        0
971           0        0
972           0        0
973           0        0
974           1        0
975           0        0
976           0        0
977           0        0
978           0        0
979           0        0
980           0        0
981           1        0
982           1        0
983           0        0
984           0        0
985           0        0
986           0        0
987           0        0
988           1        0
989           0        0
990           0        0
991           0        0
992           0        0
993           1        0
994           1        0
995           0        0
996           1        0
997           0        0
998           1        0
999           0        0

[1000 rows x 29 columns]

In [5]:
print(y)

OBS#
0       1169
1       5951
2       2096
3       7882
4       4870
5       9055
6       2835
7       6948
8       3059
9       5234
10      1295
11      4308
12      1567
13      1199
14      1403
15      1282
16      2424
17      8072
18     12579
19      3430
20      2134
21      2647
22      2241
23      1804
24      2069
25      1374
26       426
27       409
28      2415
29      6836
       ...
970     1514
971     7393
972     1193
973     7297
974     2831
975     1258
976      753
977     2427
978     2538
979     1264
980     8386
981     4844
982     2923
983     8229
984     2028
985     1433
986     6289
987     1409
988     6579
989     1743
990     3565
991     1569
992     1936
993     3959
994     2390
995     1736
996     3857
997      804
998     1845
999     4576
Name: AMOUNT, Length: 1000, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [9]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()

In [13]:
X_history = X.loc[:, 'HISTORY']
X_history

OBS#
0      4
1      2
2      4
3      2
4      3
5      2
6      2
7      2
8      2
9      4
10     2
11     2
12     2
13     4
14     2
15     2
16     4
17     0
18     2
19     2
20     4
21     2
22     4
23     4
24     4
25     2
26     0
27     1
28     2
29     3
      ..
970    2
971    2
972    1
973    2
974    4
975    2
976    2
977    3
978    3
979    1
980    4
981    2
982    2
983    2
984    4
985    4
986    0
987    2
988    2
989    4
990    4
991    1
992    2
993    2
994    2
995    2
996    2
997    2
998    2
999    4
Name: HISTORY, Length: 1000, dtype: int64

In [14]:
X_train_history, X_test_history, y_train, y_test = train_test_split(X_history, y, test_size = 0.2)

In [15]:
lr_model.fit(X=X_train_history, y=y_train)

/home/snu/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

ValueError: Found input variables with inconsistent numbers of samples: [1, 800]

In [16]:
from sklearn.neighbors import KNeighborsRegressor
n_neighbors = 5
knn_model = KNeighborsRegressor(n_neighbors = n_neighbors, weights = 'distance')

In [17]:
knn_model.fit(X_train_history, y_train)

/home/snu/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

ValueError: Found input variables with inconsistent numbers of samples: [1, 800]

In [19]:
dummified_X_history = pd.get_dummies(X_history)

In [20]:
knn_model.fit(dummified_X_history, y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='distance')

In [21]:
lr_model.fit(dummified_X_history, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [24]:
from sklearn.svm import LinearSVR
C = 1.0
svm_model = LinearSVR(C=C)

In [29]:
svm_model.fit(X=dummified_X_history,y = y)

LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_intercept=True,
     intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
     random_state=None, tol=0.0001, verbose=0)

In [38]:
dummified_X_history.shape, y.shape

AttributeError: 'tuple' object has no attribute 'transpose'

In [42]:
dummified_X_history = pd.DataFrame(dummified_X_history)

In [49]:
dht = dummified_X_history.transpose()
dht.shape

(5, 1000)

In [51]:
from sklearn import svm
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf,y,dht, cv=5)

ValueError: Found input variables with inconsistent numbers of samples: [1000, 5]